version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:18.04.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install build dependencies
          command: |
            apk add --no-cache py-pip>=9.0.0
            pip install docker-compose==1.17.1
      - run:
          name: Run unittests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
